# docker compose up

version: "3.1"

services:
  app:
    build: .
    container_name: nightscout-sisensingcgm-uploader
    environment:
      PYTHONUNBUFFERED: 1
    command: python -u package/main.py
    volumes:
      - .:/app